# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymovieshelf', '0004_auto_20171212_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='length',
            field=models.CharField(max_length=50),
        ),
    ]
