# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pymovieshelf', '0006_auto_20180209_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='url',
            field=models.URLField(default='http://blue-ray.win/pymovieshelf/'),
        ),
    ]
